name: Deploy to Docker Repository

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/projects:Responsive-Website-Design -f Src-Image/Dockerfile Src-Image  

    - name: Docker Login
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Dockerhub Public Repo
      run: docker push ${{ secrets.DOCKER_USERNAME }}/projects:Responsive-Website-Design

    - name: Update Docker Image Tag
      run: docker tag ${{ secrets.DOCKER_USERNAME }}/projects:Responsive-Website-Design ${{ secrets.DOCKER_USERNAME }}/team-projects:Responsive-Website-Design

    - name: Push Docker image to Dockerhub Private Repo
      run: docker push ${{ secrets.DOCKER_USERNAME }}/team-projects:Responsive-Website-Design








